services:
  - type: web
    name: faucet-automation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
