services:
  - type: web
    name: faucet-automation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --bind 0.0.0.0:$PORT
    autoDeploy: true
